version: '3.7'

services:
  node-chrome:
    image: selenium/node-chrome:4.11.0-20230801
    ports:
      - "5555:5555"
    environment:
      - SE_EVENT_BUS_HOST=35.222.251.116
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_HOST=35.222.251.116
      - SE_NODE_MAX_SESSIONS=12
    shm_size: '2g'
