apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: efiss-ingress
spec:
  rules:
  - host: efiss.tech
    http:
      paths:
      - path: /ai(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: ai
            port:
              number: 5000
  - host: k8s.efiss.tech
    http:
      paths:
      - path: /ai(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: ai
            port:
              number: 5000