- op: add
  path: /spec/rules/0/http/paths/0
  value:
    path: /ai(/|$)(.*)
    pathType: Prefix
    backend:
      service:
        name: ai
        port:
          number: 5000
- op: add
  path: /spec/rules/1/http/paths/0
  value:
    path: /ai(/|$)(.*)
    pathType: Prefix
    backend:
      service:
        name: ai
        port:
          number: 5000