apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- ../../base
- namespace.yaml
patches:
- path: ingress.yaml
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: efiss-ingress