---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ads
  labels:
    app: ads
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ads
  template:
    metadata:
      labels:
        app: ads
    spec:
      containers:
      - name: ads
        image: asia-southeast1-docker.pkg.dev/impactful-bee-400715/efiss/ads:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 120
          timeoutSeconds: 120
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 120
          timeoutSeconds: 120
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 50051
          name: grpc
        envFrom:
        - secretRef:
            name: mysql-secret
        - configMapRef:
            name: mysql-config
        - configMapRef:
            name: app-config
        - configMapRef:
            name: product-config
        - secretRef:
            name: ads-secret
        env:
        - name: DATABASE_NAME
          value: efiss_ads
        resources:
---
apiVersion: v1
kind: Service
metadata:
  name: ads
spec:
  type: ClusterIP
  selector:
    app: ads
  ports:
  - protocol: TCP
    name: http
    port: 3000
    targetPort: 3000
  - protocol: TCP
    name: grpc
    port: 50051
    targetPort: 50051