---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: asia-southeast1-docker.pkg.dev/even-acumen-386115/efiss/auth:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
          name: http
        - containerPort: 50051
          name: grpc
        envFrom:
        - secretRef:
            name: mysql-secret
        - configmapRef:
            name: mysql-config
        - secretRef:
            name: auth-secret
        - configmapRef:
            name: app-config
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001