---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: asia-southeast1-docker.pkg.dev/even-acumen-386115/efiss/auth:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 50051
          name: grpc
        envFrom:
        - secretRef:
            name: mysql-secret
        - configMapRef:
            name: mysql-config
        - secretRef:
            name: auth-secret
        - configMapRef:
            name: app-config
        - configMapRef:
            name: mailer-config
        env:
        - name: DATABASE_NAME
          value: efiss_auth
        resources:
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
  - protocol: TCP
    name: http
    port: 3000
    targetPort: 3000
  - protocol: TCP
    name: grpc
    port: 50051
    targetPort: 50051
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  AUTH_SERVICE_GRPC_HOST: "auth"
  AUTH_SERVICE_GRPC_PORT: "50051"