apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  LISTEN_PORT: "3001"
  GRPC_LISTEN_PORT: "50051"
  CLIENT_URL: https://efiss.tech
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  DATABASE_TYPE: mysql
  DATABASE_PORT: "3306"
  DATABASE_NAME: efiss_auth
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: productdb-config
---