apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: efiss-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: efiss.tech
    http:
      paths:
      - path: /auth
        pathType: Prefix
        backend:
          serviceName: auth
          servicePort: 3001
      - path: /search
        pathType: Prefix
        backend:
          serviceName: search
          servicePort: 3001
      - path: /product
        pathType: Prefix
        backend:
          serviceName: product
          servicePort: 3001
      - path: /normal-user
        pathType: Prefix
        backend:
          serviceName: normal-user
          servicePort: 3001
