apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: efiss-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"  # 500 MB image size limit
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"  # 10 minutes
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - efiss.tech
    - k8s.efiss.tech
    secretName: efiss-tls
  rules:
  - host: efiss.tech
    http:
      paths:
      - path: /admin(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: admin
            port:
              number: 3000
      - path: /auth(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: auth
            port:
              number: 3000
      - path: /product(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: product
            port:
              number: 3000
      - path: /search(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: search
            port:
              number: 3000
      - path: /normal-user(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: normal-user
            port:
              number: 3000
      - path: /ads(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: ads
            port:
              number: 3000
  - host: k8s.efiss.tech
    http:
      paths:
      - path: /admin(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: admin
            port:
              number: 3000
      - path: /auth(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: auth
            port:
              number: 3000
      - path: /product(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: product
            port:
              number: 3000
      - path: /search(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: search
            port:
              number: 3000
      - path: /normal-user(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: normal-user
            port:
              number: 3000
      - path: /ads(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: ads
            port:
              number: 3000