---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer
  labels:
    app: mailer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailer
  template:
    metadata:
      labels:
        app: mailer
    spec:
      containers:
      - name: mailer
        image: asia-southeast1-docker.pkg.dev/even-acumen-386115/efiss/mailer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
          name: grpc
        envFrom:
        - secretRef:
            name: mail-secret
        - configMapRef:
            name: app-config
        env:
        - name: REDIS_HOST
          value: mailer-redis
        - name: REDIS_PORT
          value: "6379"
        - name: SMTP_HOST
          value: smtp.gmail.com
        - name: SMTP_PORT
          value: "587"
        resources:
---
apiVersion: v1
kind: Service
metadata:
  name: mailer
spec:
  type: ClusterIP
  selector:
    app: mailer
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer-redis
  labels:
    app: mailer-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailer-redis
  template:
    metadata:
      labels:
        app: mailer-redis
    spec:
      containers:
      - name: mailer-redis
        image: redis
        ports:
        - containerPort: 6379
          name: redis
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: mailer-redis
spec:
  type: ClusterIP
  selector:
    app: mailer-redis
  ports:
  - protocol: TCP
    port: 6389
    targetPort: 6379
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mailer-config
  labels:
    app: mailer-config
data:
  MAILER_SERVICE_GRPC_HOST: mailer
  MAILER_SERVICE_GRPC_PORT: "50051"