---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: normal-user
  labels:
    app: normal-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: normal-user
  template:
    metadata:
      labels:
        app: normal-user
    spec:
      containers:
      - name: normal-user
        image: asia-southeast1-docker.pkg.dev/even-acumen-386115/efiss/normal-user:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 50051
          name: grpc
        envFrom:
        - secretRef:
            name: mysql-secret
        - configMapRef:
            name: mysql-config
        - configMapRef:
            name: app-config
        env:
        - name: DATABASE_NAME
          value: efiss_normal_user
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: normal-user
spec:
  type: ClusterIP
  selector:
    app: normal-user
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000