---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: product:latest
        ports:
        - containerPort: 50051
          name: grpc
        env:
        - name: DATABASE_HOST
          value: "mysql.efiss.tech"
        - name: DATABASE_PORT
          value: "3306"
        - name: DATABASE_USER
          value: "root"
        - name: DATABASE_PASSWORD
          value: "root"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: product
spec:
  type: ClusterIP
  selector:
    app: product
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051