---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: asia-southeast1-docker.pkg.dev/even-acumen-386115/efiss/product:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 50051
          name: grpc
        envFrom:
        - secretRef:
            name: productdb-secret
        - configMapRef:
            name: app-config
        resources:
---
apiVersion: v1
kind: Service
metadata:
  name: product
spec:
  type: ClusterIP
  selector:
    app: product
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  - protocol: TCP
    port: 50051
    targetPort: 50051
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
data:
  PRODUCT_SERVICE_GRPC_HOST: "product"
  PRODUCT_SERVICE_GRPC_PORT: "50051"