---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  labels:
    app: search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
      - name: search
        image: asia-southeast1-docker.pkg.dev/even-acumen-386115/efiss/search:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
          name: http
        - containerPort: 50051
          name: grpc
        env:
        - name: PRODUCT_DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: productdb-secret
              key: DATABASE_HOST
        - name: PRODUCT_DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: productdb-secret
              key: DATABASE_PORT
        - name: PRODUCT_DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: productdb-secret
              key: DATABASE_USERNAME
        - name: PRODUCT_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: productdb-secret
              key: DATABASE_PASSWORD
        - name: PRODUCT_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: productdb-secret
              key: DATABASE_NAME
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: search
spec:
  type: ClusterIP
  selector:
    app: search
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001