name: Kubernetes Cluster Deployment production

on:
  workflow_dispatch:

jobs:

  setup:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Create SSL certs
      run: 'echo "$TLS_CERT" > base/tls-cert.yaml'
      shell: bash
      env:
        TLS_CERT: ${{ secrets.TLS_CERT }}
    
    - name: Create cluster secrets
      run: 'echo "$secret" > base/secret.yaml'
      shell: bash
      env:
          secret: ${{ vars.SECRET }}
    
  deploy:
    name: Deploy Production
    needs: setup
    runs-on: self-hosted

    steps:
    - name: Make sure ingress-nginx is configured
      run: kubectl apply -k helm
      shell: bash

    - name: Apply changed kubernetes configs
      run: kubectl apply -k environments/production
      shell: bash

    - name: Deploy changed microservices
      # https://stackoverflow.com/questions/40366192/kubernetes-how-to-make-deployment-to-update-image
      run: kubectl -n prod rollout restart deployment
      shell: bash
